# Generated by Django 5.2.3 on 2025-07-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Service Manager'), ('engineer', 'Service Engineer'), ('accountant', 'Accountant'), ('tally', 'Tally User')], max_length=20),
        ),
    ]
