# Generated by Django 5.2.3 on 2025-07-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
    ]
