# Generated by Django 5.2.4 on 2025-07-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_complaint_customer_address_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='longitude',
        ),
    ]
