# Generated by Django 5.2.4 on 2025-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_remove_complaint_latitude_remove_complaint_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='complaint',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='landmark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
