# Generated by Django 5.2.3 on 2025-07-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('sold_to', models.CharField(max_length=100)),
                ('sold_date', models.DateField()),
                ('installation_date', models.DateField()),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('assigned_engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.engineer')),
            ],
        ),
    ]
