# Generated by Django 5.2.3 on 2025-07-16 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assigned_engineer',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'engineer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Engineer',
        ),
    ]
